@startuml
'https://plantuml.com/sequence-diagram



title Register Grocery Item

actor User

participant Desktop_UI

participant APIGateway

participant Consul

participant GroceryItemsService

participant Zipkin

database RedisCache

database MongoDB

activate Desktop_UI
GroceryItemsService -> Consul : Register New Service
activate Consul
activate APIGateway
activate GroceryItemsService
APIGateway -> Consul : Register New Service
Consul -> GroceryItemsService : HTTP GET http://2c4d5b467db0:8080/groceryitem/api/actuator/health
GroceryItemsService -> Consul : HTTP/1.1 200 OK Output: {"status":"UP"}
deactivate GroceryItemsService
Consul -> APIGateway : HTTP GET http://3e0dddd58d13:8080/actuator/health
APIGateway -> Consul : HTTP/1.1 200 OK Output: {"status":"UP"}
deactivate Consul
deactivate APIGateway
User -> Desktop_UI : Click On Insert New Grocery Item Button
Desktop_UI -> Desktop_UI : Load And Display CreateGroceryItemFXML
Desktop_UI -> Desktop_UI : Fill Create Grocery Item Form
Desktop_UI -> Desktop_UI : Click On Register
Desktop_UI -> APIGateway : HTTP POST http://localhost:8080/groceryitem/api/v1/items
activate APIGateway
APIGateway -> Consul : lb://grocery-items-management
activate Consul
Consul -> APIGateway : ServiceInstance
deactivate Consul
APIGateway -> GroceryItemsService : Route : /groceryitem/api/** to GroceryItemsService
activate GroceryItemsService

GroceryItemsService -> RedisCache : Cache Evict All Grocery Items
activate RedisCache
GroceryItemsService -> RedisCache : Cache Put Grocery Item
deactivate RedisCache
GroceryItemsService -> MongoDB : > db.grocery-items.insertOne( { "_id": ObjectId('id'), "name": "name", "quantity": 0, "category": "category" } )
activate MongoDB
MongoDB -> GroceryItemsService : Return Inserted Grocery Item
deactivate MongoDB
GroceryItemsService -> APIGateway : ResponseEntity<GroceryItem> HTTP/1.1 200 OK
GroceryItemsService -> Zipkin : HTTP POST http://zipkin:9411/api/v2/spans
activate Zipkin
Zipkin -> GroceryItemsService : Response 202 ACCEPTED
deactivate Zipkin
deactivate GroceryItemsService
APIGateway -> Desktop_UI : ResponseEntity<GroceryItem> HTTP/1.1 200 OK
APIGateway -> Zipkin : HTTP POST http://zipkin:9411/api/v2/spans
activate Zipkin
Zipkin -> APIGateway : Response 202 ACCEPTED
deactivate Zipkin
deactivate APIGateway
User -> Desktop_UI : Visualize Notification Message
deactivate Desktop_UI











@enduml