@startuml
'https://plantuml.com/sequence-diagram



title Find All Grocery Items

actor User

participant Desktop_UI

participant APIGateway

participant Consul

participant GroceryItemsService

participant Zipkin

database RedisCache

database MongoDB

GroceryItemsService -> Consul : Register New Service
activate GroceryItemsService
activate Consul
Consul -> GroceryItemsService : HTTP GET http://2c4d5b467db0:8080/groceryitem/api/actuator/health
GroceryItemsService -> Consul : HTTP/1.1 200 OK Output: {"status":"UP"}
deactivate GroceryItemsService
APIGateway -> Consul : Register New Service
activate APIGateway
Consul -> APIGateway : HTTP GET http://3e0dddd58d13:8080/actuator/health
APIGateway -> Consul : HTTP/1.1 200 OK Output: {"status":"UP"}
deactivate APIGateway
deactivate Consul
User -> Desktop_UI : Click On Grocery Items Tree Item
Desktop_UI -> APIGateway : HTTP GET http://localhost:8080/groceryitem/api/v1/items
activate APIGateway
APIGateway -> Consul : lb://grocery-items-management
activate Consul
Consul -> APIGateway : ServiceInstance
deactivate Consul
APIGateway -> GroceryItemsService : Route : /groceryitem/api/** to GroceryItemsService
activate GroceryItemsService
GroceryItemsService -> RedisCache : Cache Hit
activate RedisCache
RedisCache -> GroceryItemsService : Return List<GroceryItem>
deactivate RedisCache
GroceryItemsService -> MongoDB : Cache Miss > db.grocery-items.find()
activate MongoDB
MongoDB -> GroceryItemsService : Return List<GroceryItem>
deactivate MongoDB
GroceryItemsService -> APIGateway : ResponseEntity<List<GroceryItem>> HTTP/1.1 200 OK
GroceryItemsService -> Zipkin : HTTP POST http://zipkin:9411/api/v2/spans
activate Zipkin
Zipkin -> GroceryItemsService : Response 202 ACCEPTED
deactivate Zipkin
deactivate GroceryItemsService
APIGateway -> Desktop_UI : ResponseEntity<List<GroceryItem>> HTTP/1.1 200 OK
APIGateway -> Zipkin : HTTP POST http://zipkin:9411/api/v2/spans
activate Zipkin
Zipkin -> APIGateway : Response 202 ACCEPTED
deactivate Zipkin
deactivate APIGateway
User -> Desktop_UI : Visualize Notification Message






@enduml