/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.lyess.grocery_items_management_common.domain;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GroceryItemResource extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4776284155725045591L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GroceryItemResource\",\"namespace\":\"com.lyess.grocery_items_management_common.domain\",\"fields\":[{\"name\":\"groceryItem\",\"type\":{\"type\":\"record\",\"name\":\"GroceryItem\",\"namespace\":\"com.lyess.grocery_items_management_common.domain.entity\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"int\"},{\"name\":\"category\",\"type\":\"string\"}]}},{\"name\":\"link\",\"type\":{\"type\":\"record\",\"name\":\"Link\",\"namespace\":\"com.lyess.grocery_items_management_common.domain.entity\",\"fields\":[{\"name\":\"rel\",\"type\":\"string\"},{\"name\":\"href\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GroceryItemResource> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GroceryItemResource> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GroceryItemResource> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GroceryItemResource> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GroceryItemResource> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GroceryItemResource to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GroceryItemResource from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GroceryItemResource instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GroceryItemResource fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private com.lyess.grocery_items_management_common.domain.entity.GroceryItem groceryItem;
  private com.lyess.grocery_items_management_common.domain.entity.Link link;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GroceryItemResource() {}

  /**
   * All-args constructor.
   * @param groceryItem The new value for groceryItem
   * @param link The new value for link
   */
  public GroceryItemResource(com.lyess.grocery_items_management_common.domain.entity.GroceryItem groceryItem, com.lyess.grocery_items_management_common.domain.entity.Link link) {
    this.groceryItem = groceryItem;
    this.link = link;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return groceryItem;
    case 1: return link;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: groceryItem = (com.lyess.grocery_items_management_common.domain.entity.GroceryItem)value$; break;
    case 1: link = (com.lyess.grocery_items_management_common.domain.entity.Link)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'groceryItem' field.
   * @return The value of the 'groceryItem' field.
   */
  public com.lyess.grocery_items_management_common.domain.entity.GroceryItem getGroceryItem() {
    return groceryItem;
  }


  /**
   * Sets the value of the 'groceryItem' field.
   * @param value the value to set.
   */
  public void setGroceryItem(com.lyess.grocery_items_management_common.domain.entity.GroceryItem value) {
    this.groceryItem = value;
  }

  /**
   * Gets the value of the 'link' field.
   * @return The value of the 'link' field.
   */
  public com.lyess.grocery_items_management_common.domain.entity.Link getLink() {
    return link;
  }


  /**
   * Sets the value of the 'link' field.
   * @param value the value to set.
   */
  public void setLink(com.lyess.grocery_items_management_common.domain.entity.Link value) {
    this.link = value;
  }

  /**
   * Creates a new GroceryItemResource RecordBuilder.
   * @return A new GroceryItemResource RecordBuilder
   */
  public static com.lyess.grocery_items_management_common.domain.GroceryItemResource.Builder newBuilder() {
    return new com.lyess.grocery_items_management_common.domain.GroceryItemResource.Builder();
  }

  /**
   * Creates a new GroceryItemResource RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GroceryItemResource RecordBuilder
   */
  public static com.lyess.grocery_items_management_common.domain.GroceryItemResource.Builder newBuilder(com.lyess.grocery_items_management_common.domain.GroceryItemResource.Builder other) {
    if (other == null) {
      return new com.lyess.grocery_items_management_common.domain.GroceryItemResource.Builder();
    } else {
      return new com.lyess.grocery_items_management_common.domain.GroceryItemResource.Builder(other);
    }
  }

  /**
   * Creates a new GroceryItemResource RecordBuilder by copying an existing GroceryItemResource instance.
   * @param other The existing instance to copy.
   * @return A new GroceryItemResource RecordBuilder
   */
  public static com.lyess.grocery_items_management_common.domain.GroceryItemResource.Builder newBuilder(com.lyess.grocery_items_management_common.domain.GroceryItemResource other) {
    if (other == null) {
      return new com.lyess.grocery_items_management_common.domain.GroceryItemResource.Builder();
    } else {
      return new com.lyess.grocery_items_management_common.domain.GroceryItemResource.Builder(other);
    }
  }

  /**
   * RecordBuilder for GroceryItemResource instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GroceryItemResource>
    implements org.apache.avro.data.RecordBuilder<GroceryItemResource> {

    private com.lyess.grocery_items_management_common.domain.entity.GroceryItem groceryItem;
    private com.lyess.grocery_items_management_common.domain.entity.GroceryItem.Builder groceryItemBuilder;
    private com.lyess.grocery_items_management_common.domain.entity.Link link;
    private com.lyess.grocery_items_management_common.domain.entity.Link.Builder linkBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.lyess.grocery_items_management_common.domain.GroceryItemResource.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.groceryItem)) {
        this.groceryItem = data().deepCopy(fields()[0].schema(), other.groceryItem);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasGroceryItemBuilder()) {
        this.groceryItemBuilder = com.lyess.grocery_items_management_common.domain.entity.GroceryItem.newBuilder(other.getGroceryItemBuilder());
      }
      if (isValidValue(fields()[1], other.link)) {
        this.link = data().deepCopy(fields()[1].schema(), other.link);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasLinkBuilder()) {
        this.linkBuilder = com.lyess.grocery_items_management_common.domain.entity.Link.newBuilder(other.getLinkBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing GroceryItemResource instance
     * @param other The existing instance to copy.
     */
    private Builder(com.lyess.grocery_items_management_common.domain.GroceryItemResource other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.groceryItem)) {
        this.groceryItem = data().deepCopy(fields()[0].schema(), other.groceryItem);
        fieldSetFlags()[0] = true;
      }
      this.groceryItemBuilder = null;
      if (isValidValue(fields()[1], other.link)) {
        this.link = data().deepCopy(fields()[1].schema(), other.link);
        fieldSetFlags()[1] = true;
      }
      this.linkBuilder = null;
    }

    /**
      * Gets the value of the 'groceryItem' field.
      * @return The value.
      */
    public com.lyess.grocery_items_management_common.domain.entity.GroceryItem getGroceryItem() {
      return groceryItem;
    }


    /**
      * Sets the value of the 'groceryItem' field.
      * @param value The value of 'groceryItem'.
      * @return This builder.
      */
    public com.lyess.grocery_items_management_common.domain.GroceryItemResource.Builder setGroceryItem(com.lyess.grocery_items_management_common.domain.entity.GroceryItem value) {
      validate(fields()[0], value);
      this.groceryItemBuilder = null;
      this.groceryItem = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'groceryItem' field has been set.
      * @return True if the 'groceryItem' field has been set, false otherwise.
      */
    public boolean hasGroceryItem() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'groceryItem' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.lyess.grocery_items_management_common.domain.entity.GroceryItem.Builder getGroceryItemBuilder() {
      if (groceryItemBuilder == null) {
        if (hasGroceryItem()) {
          setGroceryItemBuilder(com.lyess.grocery_items_management_common.domain.entity.GroceryItem.newBuilder(groceryItem));
        } else {
          setGroceryItemBuilder(com.lyess.grocery_items_management_common.domain.entity.GroceryItem.newBuilder());
        }
      }
      return groceryItemBuilder;
    }

    /**
     * Sets the Builder instance for the 'groceryItem' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.lyess.grocery_items_management_common.domain.GroceryItemResource.Builder setGroceryItemBuilder(com.lyess.grocery_items_management_common.domain.entity.GroceryItem.Builder value) {
      clearGroceryItem();
      groceryItemBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'groceryItem' field has an active Builder instance
     * @return True if the 'groceryItem' field has an active Builder instance
     */
    public boolean hasGroceryItemBuilder() {
      return groceryItemBuilder != null;
    }

    /**
      * Clears the value of the 'groceryItem' field.
      * @return This builder.
      */
    public com.lyess.grocery_items_management_common.domain.GroceryItemResource.Builder clearGroceryItem() {
      groceryItem = null;
      groceryItemBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'link' field.
      * @return The value.
      */
    public com.lyess.grocery_items_management_common.domain.entity.Link getLink() {
      return link;
    }


    /**
      * Sets the value of the 'link' field.
      * @param value The value of 'link'.
      * @return This builder.
      */
    public com.lyess.grocery_items_management_common.domain.GroceryItemResource.Builder setLink(com.lyess.grocery_items_management_common.domain.entity.Link value) {
      validate(fields()[1], value);
      this.linkBuilder = null;
      this.link = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'link' field has been set.
      * @return True if the 'link' field has been set, false otherwise.
      */
    public boolean hasLink() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'link' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.lyess.grocery_items_management_common.domain.entity.Link.Builder getLinkBuilder() {
      if (linkBuilder == null) {
        if (hasLink()) {
          setLinkBuilder(com.lyess.grocery_items_management_common.domain.entity.Link.newBuilder(link));
        } else {
          setLinkBuilder(com.lyess.grocery_items_management_common.domain.entity.Link.newBuilder());
        }
      }
      return linkBuilder;
    }

    /**
     * Sets the Builder instance for the 'link' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.lyess.grocery_items_management_common.domain.GroceryItemResource.Builder setLinkBuilder(com.lyess.grocery_items_management_common.domain.entity.Link.Builder value) {
      clearLink();
      linkBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'link' field has an active Builder instance
     * @return True if the 'link' field has an active Builder instance
     */
    public boolean hasLinkBuilder() {
      return linkBuilder != null;
    }

    /**
      * Clears the value of the 'link' field.
      * @return This builder.
      */
    public com.lyess.grocery_items_management_common.domain.GroceryItemResource.Builder clearLink() {
      link = null;
      linkBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GroceryItemResource build() {
      try {
        GroceryItemResource record = new GroceryItemResource();
        if (groceryItemBuilder != null) {
          try {
            record.groceryItem = this.groceryItemBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("groceryItem"));
            throw e;
          }
        } else {
          record.groceryItem = fieldSetFlags()[0] ? this.groceryItem : (com.lyess.grocery_items_management_common.domain.entity.GroceryItem) defaultValue(fields()[0]);
        }
        if (linkBuilder != null) {
          try {
            record.link = this.linkBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("link"));
            throw e;
          }
        } else {
          record.link = fieldSetFlags()[1] ? this.link : (com.lyess.grocery_items_management_common.domain.entity.Link) defaultValue(fields()[1]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GroceryItemResource>
    WRITER$ = (org.apache.avro.io.DatumWriter<GroceryItemResource>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GroceryItemResource>
    READER$ = (org.apache.avro.io.DatumReader<GroceryItemResource>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.groceryItem.customEncode(out);

    this.link.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.groceryItem == null) {
        this.groceryItem = new com.lyess.grocery_items_management_common.domain.entity.GroceryItem();
      }
      this.groceryItem.customDecode(in);

      if (this.link == null) {
        this.link = new com.lyess.grocery_items_management_common.domain.entity.Link();
      }
      this.link.customDecode(in);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.groceryItem == null) {
            this.groceryItem = new com.lyess.grocery_items_management_common.domain.entity.GroceryItem();
          }
          this.groceryItem.customDecode(in);
          break;

        case 1:
          if (this.link == null) {
            this.link = new com.lyess.grocery_items_management_common.domain.entity.Link();
          }
          this.link.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










