@startuml
'https://plantuml.com/use-case-diagram
left to right direction
Actor User as user

rectangle "Grocery Items Management Application" {

usecase "Grocery Items" as GroceryItemTreeItem
usecase "Swagger" as SwaggerTreeItem
usecase "Zipkin" as ZipkinTreeItem
usecase "Documentation" as DocumentationTreeItem
usecase "License" as LicenseTreeItem
usecase "About Me" as AboutMeTreeItem

usecase "Grocery Items User Interface" as GroceryItemsSummary
usecase "Edit Grocery Item" as EditGroceryItem
usecase "Delete Grocery Item" as DeleteGroceryItem
usecase "Register Grocery Item" as RegisterGroceryItem

usecase "Swagger User Interface" as SwaggerUI
usecase "Zipkin User Interface" as ZipkinUI
usecase "GitHub Documentation" as GitHubDocumentation
usecase "License View" as LicenseView
usecase "About Me Presentation" as Website

user --> GroceryItemTreeItem
user --> SwaggerTreeItem
user --> ZipkinTreeItem
user --> DocumentationTreeItem
user --> LicenseTreeItem
user --> AboutMeTreeItem

(GroceryItemTreeItem) --> (GroceryItemsSummary) : <<include>>
(GroceryItemsSummary) ..> (EditGroceryItem) : <<extends>>
(GroceryItemsSummary) ..> (DeleteGroceryItem) : <<extends>>
(GroceryItemsSummary) ..> (RegisterGroceryItem) : <<extends>>

(SwaggerTreeItem) -->(SwaggerUI) : <<include>>
(ZipkinTreeItem) --> (ZipkinUI) : <<include>>
(DocumentationTreeItem) --> (GitHubDocumentation) : <<include>>
(LicenseTreeItem) --> (LicenseView) :  <<include>>
(AboutMeTreeItem) --> (Website) : <<include>>

}

@enduml