/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.github.lyes_sefiane.grocery_items_management_common.domain.entity;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Link extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 651563741944109153L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Link\",\"namespace\":\"io.github.lyes_sefiane.grocery_items_management_common.domain.entity\",\"fields\":[{\"name\":\"rel\",\"type\":\"string\"},{\"name\":\"href\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Link> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Link> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Link> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Link> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Link> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Link to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Link from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Link instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Link fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence rel;
  private java.lang.CharSequence href;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Link() {}

  /**
   * All-args constructor.
   * @param rel The new value for rel
   * @param href The new value for href
   */
  public Link(java.lang.CharSequence rel, java.lang.CharSequence href) {
    this.rel = rel;
    this.href = href;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return rel;
    case 1: return href;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: rel = (java.lang.CharSequence)value$; break;
    case 1: href = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'rel' field.
   * @return The value of the 'rel' field.
   */
  public java.lang.CharSequence getRel() {
    return rel;
  }


  /**
   * Sets the value of the 'rel' field.
   * @param value the value to set.
   */
  public void setRel(java.lang.CharSequence value) {
    this.rel = value;
  }

  /**
   * Gets the value of the 'href' field.
   * @return The value of the 'href' field.
   */
  public java.lang.CharSequence getHref() {
    return href;
  }


  /**
   * Sets the value of the 'href' field.
   * @param value the value to set.
   */
  public void setHref(java.lang.CharSequence value) {
    this.href = value;
  }

  /**
   * Creates a new Link RecordBuilder.
   * @return A new Link RecordBuilder
   */
  public static io.github.lyes_sefiane.grocery_items_management_common.domain.entity.Link.Builder newBuilder() {
    return new io.github.lyes_sefiane.grocery_items_management_common.domain.entity.Link.Builder();
  }

  /**
   * Creates a new Link RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Link RecordBuilder
   */
  public static io.github.lyes_sefiane.grocery_items_management_common.domain.entity.Link.Builder newBuilder(io.github.lyes_sefiane.grocery_items_management_common.domain.entity.Link.Builder other) {
    if (other == null) {
      return new io.github.lyes_sefiane.grocery_items_management_common.domain.entity.Link.Builder();
    } else {
      return new io.github.lyes_sefiane.grocery_items_management_common.domain.entity.Link.Builder(other);
    }
  }

  /**
   * Creates a new Link RecordBuilder by copying an existing Link instance.
   * @param other The existing instance to copy.
   * @return A new Link RecordBuilder
   */
  public static io.github.lyes_sefiane.grocery_items_management_common.domain.entity.Link.Builder newBuilder(io.github.lyes_sefiane.grocery_items_management_common.domain.entity.Link other) {
    if (other == null) {
      return new io.github.lyes_sefiane.grocery_items_management_common.domain.entity.Link.Builder();
    } else {
      return new io.github.lyes_sefiane.grocery_items_management_common.domain.entity.Link.Builder(other);
    }
  }

  /**
   * RecordBuilder for Link instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Link>
    implements org.apache.avro.data.RecordBuilder<Link> {

    private java.lang.CharSequence rel;
    private java.lang.CharSequence href;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.github.lyes_sefiane.grocery_items_management_common.domain.entity.Link.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.rel)) {
        this.rel = data().deepCopy(fields()[0].schema(), other.rel);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.href)) {
        this.href = data().deepCopy(fields()[1].schema(), other.href);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Link instance
     * @param other The existing instance to copy.
     */
    private Builder(io.github.lyes_sefiane.grocery_items_management_common.domain.entity.Link other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.rel)) {
        this.rel = data().deepCopy(fields()[0].schema(), other.rel);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.href)) {
        this.href = data().deepCopy(fields()[1].schema(), other.href);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'rel' field.
      * @return The value.
      */
    public java.lang.CharSequence getRel() {
      return rel;
    }


    /**
      * Sets the value of the 'rel' field.
      * @param value The value of 'rel'.
      * @return This builder.
      */
    public io.github.lyes_sefiane.grocery_items_management_common.domain.entity.Link.Builder setRel(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.rel = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'rel' field has been set.
      * @return True if the 'rel' field has been set, false otherwise.
      */
    public boolean hasRel() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'rel' field.
      * @return This builder.
      */
    public io.github.lyes_sefiane.grocery_items_management_common.domain.entity.Link.Builder clearRel() {
      rel = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'href' field.
      * @return The value.
      */
    public java.lang.CharSequence getHref() {
      return href;
    }


    /**
      * Sets the value of the 'href' field.
      * @param value The value of 'href'.
      * @return This builder.
      */
    public io.github.lyes_sefiane.grocery_items_management_common.domain.entity.Link.Builder setHref(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.href = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'href' field has been set.
      * @return True if the 'href' field has been set, false otherwise.
      */
    public boolean hasHref() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'href' field.
      * @return This builder.
      */
    public io.github.lyes_sefiane.grocery_items_management_common.domain.entity.Link.Builder clearHref() {
      href = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Link build() {
      try {
        Link record = new Link();
        record.rel = fieldSetFlags()[0] ? this.rel : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.href = fieldSetFlags()[1] ? this.href : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Link>
    WRITER$ = (org.apache.avro.io.DatumWriter<Link>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Link>
    READER$ = (org.apache.avro.io.DatumReader<Link>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.rel);

    out.writeString(this.href);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.rel = in.readString(this.rel instanceof Utf8 ? (Utf8)this.rel : null);

      this.href = in.readString(this.href instanceof Utf8 ? (Utf8)this.href : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.rel = in.readString(this.rel instanceof Utf8 ? (Utf8)this.rel : null);
          break;

        case 1:
          this.href = in.readString(this.href instanceof Utf8 ? (Utf8)this.href : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










